#%RAML 1.0 Library
usage: provides a set of reusable data types that commonly occur in geo  definitions


types: 
  geoObject:
     type: object
     properties:
       latitude:
        displayName: latitude
        description: latitude detail
        type: number
       longitutde:
        displayName: longitutde
        description:  longitutde details
        type: number


     


       