#%RAML 1.0 Library
usage: provides a set of reusable data types that commonly occur in terminal  definitions.

types:
 id:
   type: string
   description: |
      terminal id 
   maxLength: 70
   pattern: ^[a-zA-Z0-9][-a-zA-Z0-9]*$
 name:
  type: string
  description: |
      terminal name 
  maxLength: 100
     
