#%RAML 1.0 Library
usage: provides resuable datatypes for order type

types:
  orderType:
     type: string
     description: |
      stores the order type whether Dine-in or take-away
     maxLength: 50