#%RAML 1.0 Library

usage: common reusable customer details

  
types:
  name:
    type: string
    maxLength: 100
  contactNo:
    type: string
    maxLength: 10
  emailId:
    type: string
    maxLength: 100
    
      


  