#%RAML 1.0 Library
usage: provides a set of reusable data types that commonly occur in address definitions


types: 
  address1:
   displayName: address1
   description: address line 1
   maxLength: 100
   type: string
  address2:
   displayName: address2
   description: address line 2
   maxLength: 100
   type: string
  address3:
   displayName: address3
   description: address line 3
   maxLength: 100
   type: string
  address4:
   displayName: address4
   description: address line 4
   type: string
  address5:
   displayName: address5
   description: address line 5
   maxLength: 100
   type: string
  address6:
   displayName: address6
   description: address line 6
   type: string
  locality:
   displayName: locality
   description:  locality
   maxLength: 100
   type: string
  city:
   displayName: city
   description: city name
   maxLength: 100
   type: string
  zip_code:
   displayName: zip_code
   description: zip_code name
   maxLength: 100
   type: string
  country:
   displayName: country
   description: country name
   maxLength: 100
   type: string




     


       