#%RAML 1.0 Library
usage: provides a set of reusable data types that commonly occur in schedule times definitions
types: 
 schedule_times:
  properties:
    eta_for_pickup:
     displayName: eta_for_pickup
     description: 
     type: string
     maxLength: 30
    eta_to_drop:
     displayName: eta_to_drop
     description: 
     type: string
     maxLength: 30
    total_eta:
     displayName: total_eta
     description: 
     type: string
     maxLength: 30
     
