#%RAML 1.0 Library
usage: provides a set of reusable data types that commonly occur in store  definitions.

types: 
 id:
  displayName: id
  description: id of the store
  type: string
  maxLength: 70
 name: 
  displayName: name
  description: name of the store
  type: string
  maxLength: 150
       